### ISSUE TITLE
N163 Volume Bug

### ISSUE THREAD

**Issue by recolorme** [Gumball2415/j0CC-FamiTracker#174]
When opening a saved module that is using the N163 expansion, the volume for the expansion chip is extremely low. Currently, I found that there are 3 workarounds that fix the issue:

1. Turning on/off N163 multiplexer emulation via Ctrl+Shift+M.

2. Turning on/off hardware-based mixing in the Module Properties setting.

3. Moving the N163 Device mix offset slider up/down in the Module Properties settings.

**Comment by Firespike33** [comment]
Not sure if this should be considered a separate issue, but APU1 and APU2 are also about 3 dB too loud in N163 modules when hardware-accurate mixing is unchecked (compared to 0.4.0.1).

**Comment by Gumball2415** [comment]
this is due to data races when computing the legacy mix level for N163, as it's dependent on the number of channels in use by the N163. the mix is set *before* the N163 is configured with the channel count, so it thinks that it's playing 1 channel instead of the actual channels present.
a temporary fix is to load the module, then hit F12 before playing.
