### ISSUE TITLE
Assertion fail causing crash

### ISSUE THREAD

**Issue by freq-mod** [Gumball2415/j0CC-FamiTracker#209]
![ftcrash](https://user-images.githubusercontent.com/32672779/235361080-713429eb-b1da-4778-80f1-59d23c76d2a1.PNG)
I don't exactly remember what has caused this, it was some time ago. Might try to reproduce this

**Comment by Gumball2415** [comment]
Assertion fail at https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/blob/main/Source/FamiTrackerView.cpp#L1795 it seems

Are you using a release build or beta build?

**Comment by freq-mod** [comment]
It was a nightly build from appveyor (97cd125)

**Comment by N-SPC700** [comment]
Was able to reproduce. Simply click the double arrow indicator in the main pattern index twice.

![image](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/38848267/eb0d7e3d-3f58-4346-9b6f-affa61fbfffa)

**Comment by Gumball2415** [comment]
This assertion fail appears to happen only on debug builds

**Comment by Gumball2415** [comment]
When the cursor points to the `>>` in the frame editor, [the selected channel is -1](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/blob/main/Source/FrameEditor.cpp#L906). This causes the assertion to fail because the `CFamiTrackerView::SelectChannel()` function casts this value to an unsigned integer, thus  `0xffffffff` is greater than MAX_CHANNELS.
