### ISSUE TITLE
Github Release artifacts  as .zip 

### ISSUE THREAD

**Issue by superusercode** [Gumball2415/j0CC-FamiTracker#217]
This way an install of 7zip is not needed prior and allows for easier addition to community package managers like chocolatey/scoop/winget. winget submission would benefit all users as it removes the smartscreen warning which would otherwise have to be requested manually at https://www.microsoft.com/en-us/wdsi/filesubmission .

**Comment by N-SPC700** [comment]
For winget, it's probably better to use actual releases since they are confirmed stable. Using build artifacts is a huge waste of time because someone will download some random build that's possibly horribly busted. Of course, this is assuming your wording refers to those. Use the actual releases.

As for not using 7z... why? Anyone with a mouse and keyboard can install and run 7-zip or Winrar out of the box, and it keeps filesizes down. If you're extremely adamant about not using .7z on a specific PC, use an online extractor, as those exist. Search "online 7z extractor" on a search engine of choice. Or, download the source code (in a .zip) and compile that. Lots of other places and developers use .7z and I don't see anyone complaining about _them_ using that archive format. So it's not an issue.

**Comment by superusercode** [comment]
Thanks

**Comment by superusercode** [comment]
> We have added native support for additional archive formats, including tar, 7-zip, rar, gz and many others using the libarchive open-source project. You now can get improved performance of archive functionality during compression on Windows.
https://blogs.windows.com/windowsdeveloper/2023/05/23/bringing-the-power-of-ai-to-windows-11-unlocking-a-new-era-of-productivity-for-customers-and-developers-with-windows-copilot-and-dev-home/

I didn't realize this was coming out. Sorry I asked about this.
