### ISSUE TITLE
N163 lowpass filter doesn't affect multiplexer hiss

### ISSUE THREAD

**Issue by Firespike33** [Gumball2415/j0CC-FamiTracker#233]
N163 multiplexer hiss is fully present even with the new lowpass filter. I tested this with +TEK's cover of Ace's Back from Eschatos, which is 8-channel. Filter cutoff was at 12kHz, well below the hissing at 15k. The problem persists even when turning the filter down to 7k.

Module: https://drive.google.com/file/d/1Zphrc6movSZq59pUpimCQuRyjplhLB4G/view?usp=sharing

0.4.0.1 render: https://drive.google.com/file/d/17hUyRjwE_VNeS7sAYmBTe8046LM0kLIs/view?usp=sharing

0.5.0.1 render: https://drive.google.com/file/d/1Iygea9zhq-rHT5BmSex1C2Bye7-dAgsL/view?usp=sharing

(If there are issues with Google Drive I can reupload on another site)

Spectrogram (0.4.0.1 render):
![spek_PNtqd5UwUu](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/121133022/155f3874-fadd-4b7d-9355-7fcd4fadd2c2)

Spectrogram (0.5.0.1 render):
![spek_yLM9FXgs8N](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/121133022/0f6ae6ef-a78a-4163-b235-98a229ddc1f7)

**Comment by Gumball2415** [comment]
two factors has affected this:
- the new Mesen N163 emulation core #152
- lowpassing does not necessarily remove hissing, as by its nature, lowpassing happens as a curve.

in the meantime, you could either disable multiplexing or try a lower lowpass frequency

**Comment by N-SPC700** [comment]
I just played this back on a real N163 cartridge. Unsurprisingly, the result is horribly hissy.

In the tracker, lowpassing it doesn't work, but there is a multiplexer toggle built into the tracker. For hardware recordings, I often notch out the main multiplexing frequency with a [frequency list](https://www.nesdev.org/wiki/Namco_163_audio#Channel_Update) that gives me the multiplexer frequencies to filter out. Still not perfect, but it really does solve the biggest issue. Probably suitable if the multiplexer must be left on, I guess.

Simply lowpassing the multiplexer won't work, as lowpassing only gets stronger the higher you go. A notch filter, however, stops the undesired frequency right in its tracks.

Again, the simplest solution is simply turning the multiplexer off using the tracker's own multiplexer toggle feature.

I personally don't hear an issue otherwise. The playback sounds as intended, especially relative to hardware.

**Comment by Firespike33** [comment]
I specifically remember Persune mentioning that the lowpass would take care of the multiplexer hiss, so I kinda thought that's what it was for. If that's not gonna happen I can just keep notch filtering songs or disabling it though.

**Comment by Gumball2415** [comment]
the lowpass filter was meant to emulate the (poorly designed) RC lowpass filters on real N163 carts, if you rely on it to filter multiplexing, set the cutoff frequency lower to account for the rolloff

**Comment by Firespike33** [comment]
Fair, I guess I should close this then.
