### ISSUE TITLE
x64-build crash with NoRecentDocsHistory enabled in registry

### ISSUE THREAD

**Issue by eugene-s-nesdev** [Gumball2415/j0CC-FamiTracker#243]
Step-by-step:
- download lastest 0.5.0.1 x64 release
- start famitracker and select "file->recent files"
- program will be crash immediately:
![crash](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/13199529/4bae647f-bb79-4125-aa74-a8528a88f63c)

Minidump:
[MiniDump_20231128-1705-v0_5_0_1.dmp](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/files/13489075/MiniDump_20231128-1705-v0_5_0_1.dmp)

Same bug happens on j0cc-famitracker 0.6.3 x64 bit

**Comment by Gumball2415** [comment]
[this is what's executed](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/blob/633eaec0bc6d5358514ab51450186c247102a7ce/Source/FamiTracker.cpp#L456) when you select `File->Recent files`

```cpp
void CFamiTrackerApp::OnUpdateRecentFiles(CCmdUI *pCmdUI)		// // //
{
	// https://www.codeguru.com/cpp/controls/menu/miscellaneous/article.php/c167
	// updating a submenu?
	if (pCmdUI->m_pSubMenu != NULL) return;

	m_pRecentFileList->UpdateMenu(pCmdUI);		// access violation here!!
}
```

edit: i think i've located exactly where the error might've occured

**Comment by Gumball2415** [comment]
can you try to replicate this bug in Debug builds?

**Comment by eugene-s-nesdev** [comment]
Yes, i've replicated it on two laptops and one desktop machines. Debug build crashed without any warning messages. Only x64 affected.

**Comment by eugene-s-nesdev** [comment]
Fixed with your commit!
***
Another bug on windows 7 not related to the previous one (0.5.0.1 x86 official, and lastest x64 build):
1. start famitracker
2. load song, then another song, then third song, etc
3. "recent" list still empty
4. clear list manually
5. repeat step 2
6. recent list working until next famitracker reboot.
***
https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/13199529/85742507-f084-496b-9d77-567af0b9114c

**Comment by Gumball2415** [comment]
~~please list this as a separate issue so the changelog won't get cluttered~~
nvm, this is also part of the bug apparently

**Comment by nyanpasu64** [comment]
works on my machine
![Dn-FamiTracker_7ncT9ioYB6](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/913957/c9c05876-dbac-43b8-b7f5-9065b6cb9dda)

`m_pRecentFileList` is defined by MFC rather than FT, and is normally initialized by MFC itself. We only touch it in `CFamiTrackerApp::OnRecentFilesClear()`, which explains why clearing recents makes it work again. I have not finished reading the MFC code (eg. `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\atlmfc\src\mfc\appcore.cpp`) to see *why* the variable is not initialized.

My initial guess is the recent apps list is not saved properly into the registry? Can you check that registry key `HKEY_CURRENT_USER\Software\Dn-FamiTracker\Recent File List` is present, and you can use Regedit to edit the File# strings inside? If that works the problem may be permissions, or something else.

----

EDIT: I think you've set registry key `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoRecentDocsHistory`. I don't know how you did that. We will have to find a workaround for that (either changing the code to stop assuming the recent file list exists, or initializing it manually but just not saving the files to disk).

I can reproduce this crash by creating that value as a REG_DWORD and setting to 1.

**Comment by eugene-s-nesdev** [comment]
You're absolutely right. 

I set "0" to `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoRecentDocsHistory`
Recent-list is working now. 
x64-version crash is gone also.

I have no idea why it was set to "1", maybe third-party software triggered it.

**Comment by Gumball2415** [comment]
> recent list working until next famitracker reboot.

when `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoRecentDocsHistory` is enabled, Recent Files will no longer work for all applications. To fix this, you should disable it (REG_DWORD 0x00000000)
