### ISSUE TITLE
Potential VRC6 issue

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [Gumball2415/j0CC-FamiTracker#265]
When the VRC6 pulse width is set to an even value, the Sawtooth channel operates at full volume multiplied by the current volume macro.

**Comment by nyanpasu64** [comment]
vrc6 saw has 64 volume levels, and the waveform has 7 steps (by adding the volume level to an 8-bit counter 0-6 times, which can overflow). vrc6 instruments only have 16 volume levels, which get multiplied by 2 to generate a chip volume level between 0 and 30 (even only). setting the duty cycle to an odd (not even) number adds 32 to this internal chip volume level.

this is intended behavior and probably cannot change because it would break backwards compatibility.

if you do not want this behavior, set your vrc6 instrument's volume envelope to 64 steps mode (which multiplies volumes by 2 to match 16-step mode, if you want similar volumes to the pulse channels you need a multiplier somewhere between 1.5 and 2). 64-step mode is only intended to work on saw channels, and if used on pulses the volume levels will cut off at 15.

![Dn-FamiTracker_D70YiGilq7](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/913957/acd780bc-517c-404a-92e7-87542fab04d6)
